export { default as Home } from "./home/Home"
export { default as InfoAccount } from "./infoAccount/InfoAccount"
export { default as Adidas } from "./Adidas/AdidasPage"
export { default as BoyShoes } from "./Nikle/nikePage"
export { default as ChildShoes } from "./MLB/MLBPage"
export { default as Page404 } from "./pageNotFound/Page404"
export { default as ProductDetail } from "./productDetail/ProductDetail"
export { default as Cart } from "./cart/Cart"
export { default as CheckOut } from "./checkout/CheckOut"
export { default as CheckoutSuccess } from "./checkoutSuccess/CheckoutSuccess"
export { default as MyOrder } from "./myOrder/MyOrder"
export { default as SearchResult } from "./searchResult/SearchResult"
export { default as Review } from "./review/Review"

